In [4]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [5]:
data = pd.read_csv('DIABETES.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        0  
1                     0.351   31        1  
2                     0.672   32        1  
3                     0.167   21        1  
4                     2.288   33        1

In [27]:
data.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   

     DiabetesPedigreeFunction  Age  Outcome  
747                     1.096   32        0  
748                     0.408   36        1  
749                     0.178   50        1  
750                     1.182   22        1  
751                     0.261   28        0

In [41]:
data.rename(columns={"Outcome": "Diabetes"})

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   

     DiabetesPedigreeFunction  Age  Diabetes  
0                       0.627   50         0  
1                       0.351   31         1  
2                       0.672   32         1  
3                       0.167   21         1  
4                       2.288   33         1  
..                        ...  ...       ...  
747                     1.096   32         0  
748                     0.408   36         1  
749                     0.178   50         1  
750                     1.182   22         1  
751                     0.261   28         0  

[752 rows x 9 columns]

In [29]:
data.shape

(752, 9)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 752 entries, 0 to 751
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               752 non-null    int64  
 1   Glucose                   752 non-null    int64  
 2   BloodPressure             752 non-null    int64  
 3   SkinThickness             752 non-null    int64  
 4   Insulin                   752 non-null    int64  
 5   BMI                       752 non-null    float64
 6   DiabetesPedigreeFunction  752 non-null    float64
 7   Age                       752 non-null    int64  
 8   Outcome                   752 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 53.0 KB


In [6]:
data.count()

Pregnancies                 752
Glucose                     752
BloodPressure               752
SkinThickness               752
Insulin                     752
BMI                         752
DiabetesPedigreeFunction    752
Age                         752
Outcome                     752
dtype: int64

In [53]:
data_with_nan = np.where(data == 0, np.nan, data)

In [57]:
data_with_nan

array([[6.000e+00, 1.480e+02, 7.200e+01, ..., 6.270e-01, 5.000e+01,
              nan],
       [1.000e+00, 8.500e+01, 6.600e+01, ..., 3.510e-01, 3.100e+01,
        1.000e+00],
       [8.000e+00, 1.830e+02, 6.400e+01, ..., 6.720e-01, 3.200e+01,
        1.000e+00],
       ...,
       [6.000e+00, 1.620e+02, 6.200e+01, ..., 1.780e-01, 5.000e+01,
        1.000e+00],
       [4.000e+00, 1.360e+02, 7.000e+01, ..., 1.182e+00, 2.200e+01,
        1.000e+00],
       [1.000e+00, 1.210e+02, 7.800e+01, ..., 2.610e-01, 2.800e+01,
              nan]])

In [64]:
data_with_nan.mean()
df = pd.DataFrame(data_with_nan)

In [65]:
df.mean()

0      4.491446
1    121.566265
2     72.301255
3     29.251880
4    151.729381
5     32.441970
6      0.475391
7     33.144947
8      1.000000
dtype: float64

In [46]:
data.mean()

Pregnancies                   3.840426
Glucose                     120.757979
BloodPressure                68.936170
SkinThickness                20.694149
Insulin                      78.285904
BMI                          31.967420
DiabetesPedigreeFunction      0.474126
Age                          33.144947
Outcome                       0.388298
dtype: float64

In [52]:
X = data.iloc[:, :-1].values
Y = data.iloc[:, -1]


array([[6.000e+00, 1.480e+02, 7.200e+01, ..., 3.360e+01, 6.270e-01,
        5.000e+01],
       [1.000e+00, 8.500e+01, 6.600e+01, ..., 2.660e+01, 3.510e-01,
        3.100e+01],
       [8.000e+00, 1.830e+02, 6.400e+01, ..., 2.330e+01, 6.720e-01,
        3.200e+01],
       ...,
       [6.000e+00, 1.620e+02, 6.200e+01, ..., 2.430e+01, 1.780e-01,
        5.000e+01],
       [4.000e+00, 1.360e+02, 7.000e+01, ..., 3.120e+01, 1.182e+00,
        2.200e+01],
       [1.000e+00, 1.210e+02, 7.800e+01, ..., 3.900e+01, 2.610e-01,
        2.800e+01]])

In [51]:
si = SimpleImputer(missing_values=0, strategy='mean')
si.fit(X[:, 3:5])
X[:, 3:5] = si.transform(X[:, 3:5])

In [45]:
print(X[:, 3:5])

[[ 35.         151.72938144]
 [ 29.         151.72938144]
 [ 29.2518797  151.72938144]
 ...
 [ 29.2518797  151.72938144]
 [ 29.2518797  151.72938144]
 [ 39.          74.        ]]
